server:
  port: 8888
spring:
  application:
    name: config-server
  security:
    user:
      name: root
      password: 1234
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configuration-data/



